## **Add Examples to merge.json**

In [2]:
#translator = translatepy.Translator(use_google=False, use_yandex=True, use_bing=True, use_reverso=True, use_deepl=True, yandex_sid_refresh=False)        
import translatepy
import pandas as pd
import oxford_api
from oxford_api import Word

### **Functions**

In [3]:
#return the same word if it can't translate
def en_es(word):
    translator = translatepy.Translator()
    gtrans=translator.translate(word,'es','en')
    palabra=gtrans.result
    translator.clean_cache()
    return palabra

#translator.example
'''
1. return a list of objects <class 'translatepy.translators.bing.Example'>
    - Note: it doent return list of strings. You need to convert to str() to use them.
2. return empty list [] if it doesnt have examples, but sometimes return None
'''
def expl_transpy(word):
    translator = translatepy.Translator()
    ex=translator.example(word,'es','en')
    if ex is None:
        ex = []
    ex = [str(x) for x in ex[:4]]
    translator.clean_cache()
    return ex

### **Read merge.json**

In [4]:
df=pd.read_json('merge.json')
df.sample(n=5)

,word,type_word,uk_ogg,us_ogg,pron,sense,infinitive,past simple,past participle,notes
3865,praise,noun,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,[preɪz],"[encaramar, magnificar, loar, enaltecer, bombe...",None,None,None,None
3522,operate,verb,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,"['ɒpəreɪt, ɒpɜ:eɪt]","[maniobrar, obrar, mover, manejar, administrar...",None,None,None,None
2786,job,noun,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,[dʒɒb],"[quehacer, menester, oficio, colocación, ocupa...",None,None,None,None
5317,trait,noun,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,[treɪt],[rasgo],None,None,None,None
1796,era,noun,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,"['ɪərə, erə]","[época, siglo, era]",None,None,None,None

## **Test**

In [5]:
word='joint'
word='survivor'
word='home'
word='hello world'
word='mom'
word='drunk'
#word='military'
from pprint import pprint
try:
    Word.get(word)
except:
    print(f'word not found: {word}')
    expl = expl_transpy(word)[:4]
    if len(expl)==0:
        print('ninguno')
        expl = None
        print(expl)
else:
    expl=Word.examples()[:4]
    if len(expl)>=4:
        print('completo')
        pprint(expl)
    
    if len(expl)<4:
        print('falta')
        pprint(expl)
        expl = expl + expl_transpy(word)[:4]
        expl = expl[:4]
        pprint(expl)
    
    if len(expl)==0:
        print('ninguno')
        expl = None
        print(expl)

completo
['She was too drunk to remember anything about the party.',
 'His only way of dealing with his problems was to go out and get drunk.',
 'They got drunk on vodka.',
 'drunk with success']

In [46]:
def get_examples(word):
    try:
        Word.get(word)
    except:
        print(f'word not found: {word}')
        expl = expl_transpy(word)[:4]
        if len(expl)>0:
            print(expl)
        else:
            print(f'ninguno: {word}')
            expl = None
            print(expl)
    else:
        expl=Word.examples()[:4]
        if len(expl)>=4:
            print(f'completo: {word}')
            pprint(expl)

        if len(expl)<4:
            print(f'falta: {word}')
            pprint(expl)
            expl = expl + expl_transpy(word)[:4]
            expl = expl[:4]
            pprint(expl)

        if len(expl)==0:
            print(f'ninguno: {word}')
            expl = None
            print(expl)
    print('#########################')

In [6]:
def get_examples(word):
    try:
        Word.get(word)
    except:
        print(f'word not found: {word}')
        expl = expl_transpy(word)[:4]
        if len(expl)==0:
            print(f'ninguno: {word}')
            expl = None
            print(expl)
        return expl
    else:
        expl=Word.examples()[:4]
        if len(expl)<4:
            print(f'falta: {word}')
            pprint(expl)
            expl = expl + expl_transpy(word)[:4]
            expl = expl[:4]
            pprint(expl)
            print('.....')
        if len(expl)==0:
            print(f'ninguno: {word}')
            expl = None
            print(expl)
        return expl
    print('#########################')

In [11]:
#df[df['word']=='celebrate']

In [12]:
#df['word'].apply(get_examples)

In [135]:
df2=df[['word']].sample(10)
import time
ti=time.time()
df2['examples']=df2['word'].apply(get_examples)
tf=time.time()
print(f'ok! in {tf-ti} seconds')
df2

falta: thesis
['Students must submit a thesis on an agreed subject within four years.',
 'The basic thesis of the book is fairly simple.',
 'These latest findings support the thesis that sexuality is determined by '
 'nature rather than choice.']
['Students must submit a thesis on an agreed subject within four years.',
 'The basic thesis of the book is fairly simple.',
 'These latest findings support the thesis that sexuality is determined by '
 'nature rather than choice.',
 'Nobody cares about your thesis anyway.']
.....
falta: trillion
[]
['I think a couple of trillion dollars a day goes ...',
 'out of a global 5.3 trillion.',
 'And there are something like 100 trillion neural connections.',
 'amounting to over 2.5 trillion spent.']
.....
ok! in 4.495097398757935 seconds

          word                                           examples
5589     water  [a glass of water, drinking water, There is ho...
5189    thesis  [Students must submit a thesis on an agreed su...
2470      hole  [He dug a deep hole in the garden., The bomb b...
4516    secure  [to secure a contract/deal/funding, The team m...
5646     which  [Which is better exercise—swimming or tennis?,...
1314    decent  [a decent meal/place to live , Mark did a dece...
4072     queue  [There were long queues at polling stations., ...
4235  religion  [Is there always a conflict between science an...
5357  trillion  [I think a couple of trillion dollars a day go...
1179   counter  [I asked the woman behind the counter if they ...

# **Multiprocessing test speed**
speed is practically the same 22 seconds per 100 words

## **pandarallel**

In [52]:
!pip install pandarallel

Requirement already satisfied: pandarallel in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.5.2)
Requirement already satisfied: dill in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandarallel) (0.3.3)

In [141]:
from pandarallel import pandarallel

pandarallel.initialize(nb_workers=100)
df2=df[['word']].sample(100)
ti=time.time()
df2['examples']=df2['word'].parallel_apply(get_examples)
tf=time.time()
print(f'ok! in {tf-ti} seconds')
df2

INFO: Pandarallel will run on 100 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
word not found: second
word not found: lead
falta: enjoyable
[]falta: locatedfalta: species

falta: fossil[]falta: philosopherfalta: manuscript


[[]
['fossils over two million years old']falta: counsellorfalta: petrolfalta: activatefalta: biographyfalta: alien'We studied the writings of the Greek philosopher Aristotle.'

[
falta: abundance




,
 []'an unpublished/original manuscript'[]
['an illegal alien', 'aliens from outer space'][]
falta: super['I went to see a debt counsellor and she agreed to come to the bank with me.']falta: bizarrefalta: overseas,
 []
'He seems to be a bit of a philosopher.'



'I read her poems in manuscript.'[]falta: thief



,

falta: naval,
 []'medieval illuminated manuscripts'[]'Many of his followers regarded him as a true philosopher.'
[]]]falta: collect[]


falta: mathematical['they had an enjoyable afternoon.']

[
falta: banner
[]

'fossils over two million years old'

falta: impressed[][
,
 .....falta: passionate'They fought the election under the banner of ‘No new taxes’.'
falta: legislaturefalta: align'We might even find the rest of your fossil.'[
,
 ,
 ['Located on first floor.''An opposing small fossil.'
'Troops are in the country under the banner of the United Nations.''It exists again in many different species.'[][[
['fumes from cooking are enough to activate the alarm.']
[
]
'to have a passionate nature',
 ,
 ,
 [[]'What a concluding chapter for your biography.',
 'Any oxidizing agent, but it does indicate petrol gasoline.''a passionate interest in music'falta: premier
,
 'Evolutionary psychology would suggest that this protects the species.']
'The student council office is also located here.'
"A shark's tooth lay near the fossil.",
 .....'Make sure the shelf is aligned with the top of the cupboard.',
 'You still smell of petrol.'
,
 ['estimates of the abundance of harp seals.'],
 'Somebody must be passing out copies of my biography.'['his behaviour became more and more bizarre.'],
 ,
 'The top and bottom line of each column on the page should align.',
 'We all originated from lesser species.''a passionate defender of civil liberties'[

'At a certain point, no more petrol.''In short, ideally located for both business and tourism.',
 ,
 [],
 .....'But he was a thief.',
 .....

,
 [[.....
'For leaving like that, like a thief.''Twenty per hour, plus petrol.''an unpublished/original manuscript'

][]'I read a biography about you.''Domestic prices have been aligned with those in world markets.''an illegal alien'],
 [,
 'But mix and match with different species.''We studied the writings of the Greek philosopher Aristotle.'
'Located in adjacent appartment building.'
'I read her poems in manuscript.''Add the money to the evidence against this thief.',
 ],
 []
'He seems to be a bit of a philosopher.',
 ],

'medieval illuminated manuscripts''aliens from outer space''He was from a naval family.''It belongs to a jewel thief.'
.....,
 [,
 ,
 .....,
 ].....'... and not one of our overseas commanders.''It must be a naval base.',
 ,

,

'... other hand, my friend, this is from overseas.''I will look at this alien.'
'I had our naval reconnaissance planes take a look.''Many of his followers regarded him as a true philosopher.',
 'More than a philosopher, then.',
 ninguno: super
"the scholar discovered a 5th century manuscript buried in the cathedral's ",
 'I have already contacted naval support.'.....
'Alien traffic is the same as ever.'

]'I wrote you the letter about the biography.'None],


]
'... were normally imported, even from overseas.'.....
'archives.'falta: neighbouring.....
,

.....
]'... one in the service overseas.'
[][
]'I was more impressed by your report.'.....

,


.....]'That also impressed me.'falta: bride
,

..........'I was impressed by your lecture at the conference.'[],




'Never seen him so impressed.']
.....
['They fought the election under the banner of ‘No new taxes’.',
 'Troops are in the country under the banner of the United Nations.',
 'campaigns fought under the banner of multiculturalism.']
.....
['The majority of the legislature consists of birds.',
 'This is an issue for the legislature.',
 'And these laws are taken seriously by the legislature.',
 'Maybe the legislature, if the right seat opens up.']
.....
["who's going to collect the kids from school?"]
.....
['to have a passionate nature',
 'a passionate interest in music',
 ['a passionate defender of civil liberties''together and seek help in the neighbouring',
 ,
 'or two of the lads at a neighbouring''You are strong, passionate and loyal to a fault.',
 ]'knocked so loud that he made the neighbouring hills resound.'
,
 'passing down the neighbouring lane might'.....]

.....
['Make sure the shelf is aligned with the top of the cupboard.',
 'The top and bottom line of each column on the page should align.',
 'Domestic prices have been aligned with those in world markets.',
 'Align the first row of ...']
.....
falta: somewhere
[]
[]
.....
ninguno: premier
None
['We have a present for the bride.',
 'Find me another bride.',
 "A bride's work is never done.",
 'Even without the bride, no problem.']
.....
['I went to see a debt counsellor and she agreed to come to the bank with me.',
 'A counsellor took up the word.',
 'A position for senior counsellor.',
 'He felt that a counsellor could help the captain in ...']
.....
['It sparks mathematical talk.',
 'This is obviously a mathematical incompatibility.',
 'The essence of nature is mathematical.',
 'It is a mathematical certainty.']
.....
[]
.....
ninguno: somewhere
None
ok! in 22.429956197738647 seconds

            word                                           examples
1380   dependent  [a woman with several dependent children, You ...
434         bank  [I don't have much money in the bank at the en...
5459      uphold  [We have a duty to uphold the law., The regime...
5012       super                                               None
1156  correction  [I've made a few small corrections to your rep...
...          ...                                                ...
732        carve  [a carved doorway, The statue was carved out o...
631        bride  [We have a present for the bride., Find me ano...
1269        cute  [a cute little baby, She's so cute!, an unbear...
4761   somewhere                                               None
1149        core  [This report goes to the core of the argument....

[100 rows x 2 columns]

## **multiprocessing.dummy**

In [42]:
df3=df[['word']].sample(100)
df3['word_id']=df3['word']
#add new empty columns
df3['examples'] = pd.Series(dtype='object')
df3.set_index('word_id',inplace=True)
df3

                      word examples
word_id
when                  when      NaN
outrage            outrage      NaN
treaty              treaty      NaN
guest                guest      NaN
serve                serve      NaN
...                    ...      ...
essentially    essentially      NaN
farmer              farmer      NaN
scandal            scandal      NaN
constitution  constitution      NaN
something        something      NaN

[100 rows x 2 columns]

In [43]:
def set_examples(word):
    df3.at[word,'examples'] = get_examples(word)

In [44]:
set_examples(df3['word'].sample(1)[0])
df3

                      word examples
word_id
when                  when      NaN
outrage            outrage      NaN
treaty              treaty      NaN
guest                guest      NaN
serve                serve      NaN
...                    ...      ...
essentially    essentially      NaN
farmer              farmer      NaN
scandal            scandal      NaN
constitution  constitution      NaN
something        something      NaN

[100 rows x 2 columns]

In [46]:
from multiprocessing.dummy import Pool as ThreadPool 
import time
ti=time.time()
a = df3['word'].tolist()

pool = ThreadPool(100)
pool.starmap(set_examples, zip(a)) 
pool.close() 
pool.join()
tf=time.time()
print(f'ok! in {tf-ti} seconds')
df3

word not found: all right
falta: accountant
['The bomb devastated much of the old part of the city.']
falta: noble
[]
falta: mercy
[]
falta: building
[]
falta: treaty
[]
['the soldiers showed no mercy on the captured enemy troops.']
.....
['The bomb devastated much of the old part of the city.',
 'The cheques goto the accountant to be processed.',
 'The accountant told me yesterday.',
 'And the accountant returns to zero.']
.....
falta: disposal
[]
falta: pioneer
[]
falta: formal
[]
ninguno: all right
None
['That is a noble cause.',
 "This guy's so noble and humble.",
 'We have found you great and noble.',
 'My father is a noble.']
.....
['the building of motorways.']
.....
["This is not a treaty that you're negotiating.",
 'And this treaty flies in the face of it.',
 'Seven out of ten volunteers out against the treaty.',
 'Then there will be no treaty.']
.....
word not found: barrierfalta: embarrassing

falta: if["But a pioneer's much nicer than a sergeant.",
 "So that's how it feels to be a pioneer.",
 'I want to pioneer the art of touching.',
 'A pioneer in hybridization.'
['The doctor told me to eat less red meat and dairy.',
 'I went to buy a paper at the corner dairy.']
]
.....
['The doctor told me to eat less red meat and dairy.',
 'I went to buy a paper at the corner dairy.']
['who is in charge of the disposal of tables and seating for the gala dinner?']
.....
['Get a formal statement.',
 'He was going to ask for a formal hearing.',
 'And on a more formal basis than hitherto.',
 'Nothing quite so formal.']
.....
['The doctor told me to eat less red meat and dairy.',
 'I went to buy a paper at the corner dairy.',
 "if you like i'll put in a word for you."]
.....
['The doctor told me to eat less red meat and dairy.',
 'I went to buy a paper at the corner dairy.',
 'Embarrassing is a better classification.',
 'I know this is embarrassing, but.']
.....
ok! in 26.617594242095947 seconds

                      word                                           examples
word_id
when                  when  [the local/national/foreign press, the popular...
outrage            outrage  [the local/national/foreign press, the popular...
treaty              treaty  [This is not a treaty that you're negotiating....
guest                guest  [Breakfast is served between 7 and 10 a.m., Wh...
serve                serve  [an intensive language course, two weeks of in...
...                    ...                                                ...
essentially    essentially  [The baby weighed three kilos at birth., Globa...
farmer              farmer  [an embarrassing moment/situation, an embarras...
scandal            scandal  [an embarrassing moment/situation, an embarras...
constitution  constitution  [The baby weighed three kilos at birth., Globa...
something        something  [I think I'll do some digging in the garden., ...

[100 rows x 2 columns]

In [47]:
get_examples('reportedly')

falta: reportedly
[]
[]
.....
ninguno: reportedly
None

# **Implementation**

In [53]:
import translatepy
import pandas as pd
import oxford_api
from oxford_api import Word

### **Functions**

In [54]:
#return the same word if it can't translate
def en_es(word):
    translator = translatepy.Translator()
    gtrans=translator.translate(word,'es','en')
    palabra=gtrans.result
    translator.clean_cache()
    return palabra

#translator.example
'''
1. return a list of objects <class 'translatepy.translators.bing.Example'>
    - Note: it doent return list of strings. You need to convert to str() to use them.
2. return empty list [] if it doesnt have examples, but sometimes return None
'''
def expl_transpy(word):
    translator = translatepy.Translator()
    ex=translator.example(word,'es','en')
    if ex is None:
        ex = []
    ex = [str(x) for x in ex[:4]]
    translator.clean_cache()
    return ex

def get_examples(word):
    try:
        Word.get(word)
    except:
        expl = expl_transpy(word)[:4]
        if len(expl)==0:
            expl = None
        return expl
    else:
        expl=Word.examples()[:4]
        if len(expl)<4:
            expl = expl + expl_transpy(word)[:4]
            expl = expl[:4]
        if len(expl)==0:
            expl = None
        return expl

### **Read file merge.json**

In [55]:
df=pd.read_json('merge.json')
df.sample(n=3)

,word,type_word,uk_ogg,us_ogg,pron,sense,infinitive,past simple,past participle,notes
4901,sticky,adjective,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,['stɪkɪ],"[pegajoso, pegadizo, viscoso, bochornoso]",None,None,None,None
2817,key,adjective,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,[ki:],"[acuñar, manipulador, tecla, llave, tono, clave]",None,None,None,None
5199,thirsty,adjective,https://www.oxfordlearnersdictionaries.com/med...,https://www.oxfordlearnersdictionaries.com/med...,['θɜ:stɪ],[sediento],None,None,None,None

## **Multiprocessing Pandarallel**

In [58]:
#pip install pandarallel
import time
from pandarallel import pandarallel

pandarallel.initialize(nb_workers=100)
df2=df[['word']].sample(50)
ti=time.time()
df2['examples']=df2['word'].parallel_apply(get_examples)
tf=time.time()
print(f'ok! in {tf-ti} seconds')
df2

INFO: Pandarallel will run on 100 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
ok! in 12.073652982711792 seconds

              word                                           examples
722         career  [a teaching career, She plans to pursue a care...
5300         track  [railway/railroad tracks, We crossed the rail/...
347      associate  [I always associate the smell of baking with m...
5586         waste  [I hate unnecessary waste., It seems such a wa...
4586   shareholder  [If it maintains that ability soon will be a s...
3117        market  [a fruit/flower/fish market , an antiques mark...
4012       protect  [to protect children/citizens/civilians/consum...
4906      stimulus  [Books provide children with ideas and a stimu...
4940        string  [a piece/length/ball of string , He wrapped th...
3616           pad  [medicated cleansing pads for sensitive skin, ...
705         canvas  [tents made from heavy canvas, a sale of the a...
2318    greenhouse  [But you sent us into the greenhouse., He saw ...
3803          poem  [Maybe you'll write a poem about this., You ex...
5208        though  [Anne was fond of Tim, though he often annoyed...
2311         grave                                               None
1617          dumb  [That was a pretty dumb thing to do., If the p...
3276       monthly  [a monthly meeting/visit/magazine, a monthly s...
48    accumulation  [the accumulation of wealth, an accumulation o...
3166         medal  [I wear the medal now., I brought you a gold m...
5625          west  [Which way is west?, Rain is spreading from th...
1442      dictator  [The country suffered at the hands of a series...
4858         stage  [I can't make a decision at this stage., At on...
2098      flourish  [Few businesses are flourishing in the present...
4203        regret  [If you don't do it now, you'll only regret it...
2739     interview  [a job interview, She's been called for (an) i...
2268        global  [This year the global economy will grow by abo...
364         attain  [Most of our students attained five ‘A’ grades...
1529    distribute  [The leaflets have been widely distributed., T...
2212         funny  [a funny story/joke, He was a very funny guy a...
5520          vice  [At the door were two plain-clothes detectives...
4205       regular  [regular breathing, a regular pulse/heartbeat,...
3084          make  [to make a table/dress/cake, to make bread/cem...
953     commission  [The commission is expected to report its find...
2645    inhabitant  [Perhaps the native inhabitant can help us., ....
3018          lock  [Did you lock the door?, David locked the car ...
1874         exert  [He exerted all his authority to make them acc...
2415       heavily  [It was raining heavily., to drink heavily, to...
4371        ritual  [religious rituals, She objects to the ritual ...
550          blank  [Sign your name in the blank space below., a b...
5130     temporary  [i was granted a temporary visa to enter the u...
497          below  [They live on the floor below., I could still ...
4221      relative  [You must consider the relative merits of the ...
165          alert  [Neighbours quickly alerted the emergency serv...
1064  considerably                   [a considerably higher density.]
5332     transport  [air/freight/road transport, the government’s ...
3996    pronounced  [We see a very pronounced hook., I have to mak...
330         aspire  [Don't aspire for material enjoyment., We shou...
4620      shortage  [the water shortage threatens to destroy most ...
841        citizen  [The defeat of the president did not change th...
660         bullet  [Only a bullet can save him., Conducts electri...